### ISSUE TITLE
[Question] How does auto-animate avoid animation debounce?

### ISSUE THREAD

**Issue by pureliumy** [formkit/auto-animate#103]
I am learning auto-animate's source code, there is a question about animation debounce.

I have a codepen demo: https://codepen.io/liumy/pen/QWrRJYB

The question is when you press enter quickly in the `ol` list, the height animation will shaking, but using auto-animate won't.

Could anyone help to explain why, much appreciate for this.

**Comment by justin-schroeder** [comment]
👋 I'll admit im not going to spend a lot of time reading the other source code, but AutoAnimate avoids (some, not all) jitter by always keeping an up to date map of the positions of all animatable elements and then peforming a FLIP transition on them. If a previous animation was in progress, auto animate cancels the flip (which does cause a jump to the end state), and runs the next animation.

Hope that helps!
