### ISSUE TITLE
Type 'RefObject<Element>' is not assignable to type 'LegacyRef<HTMLUListElement> | undefined

### ISSUE THREAD

**Issue by alexander-vashchuk** [formkit/auto-animate#108]
Can somebody explain me this issue? I'm using the code straight from the docs.

![animation](https://user-images.githubusercontent.com/86713661/203483963-2eb29278-af81-4708-bacc-3b6867c3286e.gif)

I was able to resolve it by wrapping it with MUI box wrapper, but others might not be lucky to use MUI in the project

So bringing a little bit more understanding to the issue would be welcomed

**Comment by justin-schroeder** [comment]
You can add a type argument to `useAutoAnimate`.

```ts
useAutoAnimate<HTMLUListElement>()
```
