### ISSUE TITLE
Not working with forwardRef

### ISSUE THREAD

**Issue by brokuka** [formkit/auto-animate#109]
Hello devs, i'm currently using RemixJS + TS in my project, lib don't work properly. No errors, just not working, need some help.

Here some screens:
![image](https://user-images.githubusercontent.com/75063653/204433467-b88ed246-2943-4afd-827f-196ab54b27bb.png)
![image](https://user-images.githubusercontent.com/75063653/204433508-1fc1dcee-e3b2-404c-89cd-8c0aa64b2e9a.png)

**Here works stable:**
![image](https://user-images.githubusercontent.com/75063653/204433606-dc8cc107-1c21-42b5-b90b-c11c271cad78.png)

**Comment by justin-schroeder** [comment]
I'm going to guess you have prefers reduced motion enabled. You could try passing:

```
disrespectUserMotionPreference: true
```
