### ISSUE TITLE
doesn't work with jest?

### ISSUE THREAD

**Issue by ming2024** [formkit/auto-animate#112]
created a demo repo https://github.com/ming2024/boilerplate-vite-react

no issue starting my app but failed when run `yarn test` with jest

<img width="494" alt="image" src="https://user-images.githubusercontent.com/111698568/209323213-45738efb-db39-48e0-9c7a-9f14b6f6ba8a.png">

**Comment by justin-schroeder** [comment]
Auto animate is an EMS module only — you need to run jest with module support enabled, but thats a discussion for another thread. Possibly helpful is #29
