### ISSUE TITLE
auto-animate breaks after scroll

### ISSUE THREAD

**Issue by rodakd** [formkit/auto-animate#114]
https://codesandbox.io/s/hopeful-mayer-q5zz9o

**Comment by Chen-913** [comment]
I had the same problem.
The way I reproduce it is to modify the structure of  `A quick demo` through DevTools on the [official website](https://auto-animate.formkit.com/). 
Give it a fixed height. Then set the y-axis overflow hide.
![image](https://user-images.githubusercontent.com/72293244/211455019-0982ade1-772d-4ef5-b73f-ebd315e72f35.png) 
Then add a lot of items, then scroll to the middle, click to delete one, and this problem will occur.

**Comment by ucoban** [comment]
same issue here... is there any progress?

**Comment by foreverheavy** [comment]
I'm having this issue as well - for me, it appears to be related to the way scroll position is calculated. It does not correctly compensate for elements within a nested scroll element. A solution to this would be introducing an option to define which element the scroll offset should be calculated from
