### ISSUE TITLE
Document example with Nuxt

### ISSUE THREAD

**Issue by epigramengineer** [formkit/auto-animate#12]
From the [nuxt vue plugins documentation](https://nuxtjs.org/docs/directory-structure/plugins/#vue-plugins it would seem all I need to do to get auto-animate to work is the following:

```
❯ npx nuxi init site
❯ yarn add @formkit/auto-animate
❯ yarn install
❯ yarn nuxi add plugin autoanimate 
```

`plugins/autoanimate.ts`:
```
import Vue from 'vue'
import { autoAnimatePlugin } from '@formkit/auto-animate/vue'
Vue.use(autoAnimatePlugin)
```

nuxt.config.ts:
```
...
  plugins: ['~/plugins/autoanimate.ts']
...
```

But this doesn't seem to work, could you add an example to the documentation of how auto-animate works with nuxt?

**Comment by justin-schroeder** [comment]
The directive in Auto Animate is made for Vue 3 — Should work great with Nuxt 3, but not with Nuxt 2. However, you can pretty easily use AutoAnimate on Vue 2 by using the `autoAnimate` function with a ref — or you can define the custom directive (`v-auto-animate`) out of the box — for example:

https://codesandbox.io/s/priceless-thunder-m89xo6?file=/src/main.js

Good luck!

**Comment by Tunji-Olakunle** [comment]
how do I register the auto-animate library in nuxt 3

this is what I have in my formkit.config.ts, but it is not working

```
import { en } from '@formkit/i18n'
import { DefaultConfigOptions } from '@formkit/vue'
import { createAutoAnimatePlugin } from '@formkit/addons'
import '@formkit/themes/windicss'

const config: DefaultConfigOptions = {
  locales: { en },
  locale: 'en',
  plugins: [
    createAutoAnimatePlugin()
  ]
}

export default config
```
