### ISSUE TITLE
Unable to use AutoAnimate in Solid.js project following documentation example

### ISSUE THREAD

**Issue by andrew-boyd** [formkit/auto-animate#121]
Discord user `sigma` is unable to get AutoAnimate working in their solid.js project following our examples in the docs. 

reproduction repo here: https://github.com/awojciak/autoanimate-repro

```
npm install
npm run dev
```

Example is in `./src/components/Drawer.tsx`

**Comment by andrew-boyd** [comment]
There are two TypeScript issues in the file:

![Screenshot 2023-02-05 at 4 33 52 PM](https://user-images.githubusercontent.com/2946356/216847362-8ed75659-c544-418d-ad6b-d6462fd6c83d.png)

![Screenshot 2023-02-05 at 4 33 58 PM](https://user-images.githubusercontent.com/2946356/216847363-e16d726d-6258-47b4-867a-5b97c412c5eb.png)

**Comment by andrew-boyd** [comment]
Am able to work around this issue with the following. Notably, `import { autoAnimate } from '@formkit/auto-animate/solid'` does not work — there is no named export of `autoAnimate` from `@formkit/auto-animate/solid`.

```js
import { createSignal, For, Show } from "solid-js"
import { createAutoAnimateDirective } from "@formkit/auto-animate/solid"
import "./index.css"

export default function Drawer() {
  // Required to prevent TS from removing the directive
  const autoAnimate = createAutoAnimateDirective

  const menuItems = ["Home", "Settings", "Logout"]
  const [isExpanded, setIsExpanded] = createSignal(true)

  return (
    <div class="parent" use:autoAnimate>
      <Show when={isExpanded()} keyed>
        <ul class="drawer">
          <For each={menuItems}>{(item) => <li class="item">{item}</li>}</For>
        </ul>
      </Show>
      <div class="content">
        <button
          class="button button--alt"
          type="button"
          onClick={() => setIsExpanded((isExpanded) => !isExpanded)}
        >
          Toggle Drawer
        </button>
      </div>
    </div>
  )
}
```

**Comment by rifandani** [comment]
I'm using v1.0.0-beta.6 and yeah the example of usage in the documentation is not working both with `createAutoAnimate` and `createAutoAnimateDirective` function as of today.

The `createAutoAnimate` function is actually accepting `AutoAnimateOptions` object as it's params, not the parent ref.
It returns a tuple of ref setter and `setEnabled` setter function -> `const [setParent, setEnabled] = createAutoAnimate()`.
Then, we can use the `setParent` setter function in `ref` parent element, but set it like this -> `ref={(elem) => setParent(elem)}`

**Comment by MartinBspheroid** [comment]
> I'm using v1.0.0-beta.6 and yeah the example of usage in the documentation is not working both with `createAutoAnimate` and `createAutoAnimateDirective` function as of today.
> 
> The `createAutoAnimate` function is actually accepting `AutoAnimateOptions` object as it's params, not the parent ref. It returns a tuple of ref setter and `setEnabled` setter function -> `const [setParent, setEnabled] = createAutoAnimate()`. Then, we can use the `setParent` setter function in `ref` parent element, but set it like this -> `ref={(elem) => setParent(elem)}`

Thanks, this helped me a lot! 
Also, thanks, this rocks my socks of so far!
