### ISSUE TITLE
The following packages did not export their `package.json` file so we could not check the "svelte" field.

### ISSUE THREAD

**Issue by bottomground** [formkit/auto-animate#124]
Am trying to use on a Svelte/Sapper site and it appears to work but get the following error when building.
I see your package.json file and so am unsure next steps to take.

[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

- @formkit/auto-animate

Thanks for a great utility!

**Comment by justin-schroeder** [comment]
Interesting. Export the `package.json` eh? We can do that.

**Comment by bottomground** [comment]
Thanks, loving AutoAnimate

**Comment by justin-schroeder** [comment]
I believe this was resolved on `rollup-plugin-svelte`’s side of things: https://github.com/sveltejs/rollup-plugin-svelte/issues/181
