### ISSUE TITLE
Solid.js example not working 

### ISSUE THREAD

**Issue by s0er3n** [formkit/auto-animate#125]
I copied the example into a codesandbox and added version 1.0.0-beta.6 via yarn.

https://codesandbox.io/p/sandbox/jolly-chatterjee-6h9kvx?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A63%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A63%7D%5D

**Comment by andrew-boyd** [comment]
We're tracking this in #121, mind checking if the temporary solution there works for you in the mean time?
