### ISSUE TITLE
Pointing out the importance of correct key in the documentation

### ISSUE THREAD

**Issue by patrikzudel** [formkit/auto-animate#137]
Hello!

I think it would be useful to point out the importance of using a unique key so the animation system knows how to identify elements correctly. I struggled for a while because I used the index on an array element as a key (as React recommends that in an error). That lead to weird behaviors in the animations (as it should) which confused me at first. I think it would help fellow noobs like me to have good results straight away! 

Thanks for your work, its great!

**Comment by valgeirb** [comment]
It's already mentioned in the Vue section but maybe it could be made more prominent.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/2593027/231484100-b08aa9ab-fb3e-4535-8fc4-c14f7035b74d.png">
