### ISSUE TITLE
Animaion glitch if the last element of a list at the bottom of a page is deleted

### ISSUE THREAD

**Issue by not-an-ai** [formkit/auto-animate#139]
Occurs when the last element at the bottom of a page is deleted

1) Add elements by adding + until they move out of the screen
2) Scroll down
3) Click the lowest element to delete it

Expected result: Smooth animation

Actual result: Jumping of the screen / button

The glitching does not occur if there is enough space underneath the deleted element

_Besides that edge case, a really nice animation helper_

Set up a minimal project for debugging it: https://github.com/not-an-ai/auto-animate-glitch

**Comment by justin-schroeder** [comment]
Thanks for the great reproduction — this will be fixed in the next published version
