### ISSUE TITLE
Typescript RefObject<T> not supported (React)

### ISSUE THREAD

**Issue by arimendelow** [formkit/auto-animate#141]
Because the hook just returns `RefObject<Element>`, you'll get the following error:

<img width="1181" alt="Screenshot 2023-05-20 at 2 13 51 PM" src="https://github.com/formkit/auto-animate/assets/16390116/f2e3e0df-ca65-4f44-a69d-c4dce5207e67">

The only solution to this is to cast the ref to the required type, but it's quite silly as this should just accept a type parameter.

**Comment by justin-schroeder** [comment]
I believe this is already implemented:

```ts
function useAutoAnimate<T extends Element>(
  options?: Partial<AutoAnimateOptions> | AutoAnimationPlugin
): [RefCallback<T>, (enabled: boolean) => void]
```
