### ISSUE TITLE
version 1.0.0-beta.1 is not working

### ISSUE THREAD

**Issue by liangerwen** [formkit/auto-animate#15]
version 1.0.0-beta.1 is not working
The official website demo is also not working

**Comment by justin-schroeder** [comment]
Gonna need just a tad more than that mate

**Comment by aboutZZ** [comment]
+1

**Comment by justin-schroeder** [comment]
Do you have `prefers-reduced-motion: reduce` set on your machine? Auto animate is disabled in that case.

**Comment by aboutZZ** [comment]
> Do you have `prefers-reduced-motion: reduce` set on your machine? Auto animate is disabled in that case.

The gif above is the [official website demo](https://auto-animate.formkit.com/) , still not working, no animation

**Comment by justin-schroeder** [comment]
I understand that, but `prefers-reduced-motion: reduce` is a personal setting that can be configured on your machine. Websites will tone down or remove animations if you have this setting enabled. In the case of AutoAnimate we disable the library if this setting is enabled. It works a bit like light mode or dark mode, a system setting (or sometimes browser setting) that is system wide.

If you put this line of code into the dev tools console, what result do you get:

```
window.matchMedia('(prefers-reduced-motion: reduce)')
```

<img width="520" alt="image" src="https://user-images.githubusercontent.com/1950463/170619596-673924c7-7d2b-4429-b6c2-6417f4e7b728.png">

**Comment by aboutZZ** [comment]
Accoring to [MDN prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)

After change system settings, it works.
In Windows 10: Settings > Ease of Access > Display > Show animations in Windows.

Please close this issue.
