### ISSUE TITLE
Does it support Vue2？

### ISSUE THREAD

**Issue by lujunjian1570** [formkit/auto-animate#165]
Does it support Vue2？

**Comment by justin-schroeder** [comment]
Sure, but no directive has been written for it. Youll just need to manually use the `autoAnimate` function.

**Comment by SnakeO** [comment]
https://codesandbox.io/p/sandbox/priceless-thunder-m89xo6?file=%2Fsrc%2FApp.vue%3A3%2C9-3%2C23
