### ISSUE TITLE
List Example - Vanilla JS

### ISSUE THREAD

**Issue by pauloguerraf** [formkit/auto-animate#17]
Hi,

First of all, thank you for all your work in this library. It is pretty awesome! 

I wanted to know if would be possible for you to publish your List example but for Vanilla JS [https://github.com/formkit/auto-animate/blob/master/docs/src/examples/list/ActualList.vue](https://github.com/formkit/auto-animate/blob/master/docs/src/examples/list/ActualList.vue)

I am trying to understand animate elements transform with auto-animate in vanilla js (a hamburger menu for example) 

Thank you in advance for your help.

paulo

**Comment by justin-schroeder** [comment]
👋 hi @pauloguerraf. Here's a vanilla version, not quite as full featured but should get you pretty far: https://stackblitz.com/edit/auto-animate-vanilla-list?file=index.html,styles.css
