### ISSUE TITLE
How to import Auto-Animate into a Native HTML file without using Node.js?

### ISSUE THREAD

**Issue by AnsonCar** [formkit/auto-animate#173]
I can't find autoAnimate.js.

**Comment by justin-schroeder** [comment]
Great question! Here you go: https://codepen.io/justin-schroeder/pen/VwgayNR

**Comment by AnsonCar** [comment]
> Great question! Here you go: https://codepen.io/justin-schroeder/pen/VwgayNR
Thank you!
