### ISSUE TITLE
Support for `v-auto-animate` in Vue2

### ISSUE THREAD

**Issue by aantn** [formkit/auto-animate#18]
Hi, I'm using Vue 2. Is there a way to get `v-auto-animate` working?

If relevant, I'm using the composition API plugin for vue2.

**Comment by justin-schroeder** [comment]
Ahh yes. I've heard ancient tales of this long forgotten "Vue 2" you speak of. Legends tell of it's greatness, and single root node limitations — however, I have discovered a dusty old manuscript that may assist in your journey through the past:

https://codesandbox.io/s/priceless-thunder-m89xo6?file=/src/main.js

**Comment by aantn** [comment]
Many thanks 🙏
