### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dev2Slope** [formkit/auto-animate#183]
I have been trying to use this library with react and after many attempts I got it to work, the time I got it to work I just modified the key inside a .map() loop. The next time, without modifying anything, it didn't work anymore.

I have seen that in the documentation examples it doesn't work and in other examples on the internet either, but I find it strange that nobody has complained yet.

**Comment by Dev2Slope** [comment]
@justin-schroeder I don't know what sense it has, if each user that enters in my web has to activate this option to see animations this library is not worth for anything.

**Comment by andrew-boyd** [comment]
> if each user that enters in my web has to activate this option to see animations this library is not worth for anything.

Agreed. Fortunately the `prefers-reduced-motion` accessibly option is off by default on every device we are aware of— so you must have enabled it at some point on your own device manually.

**Comment by Dev2Slope** [comment]
Now I understand, as I had that option disabled I thought that everybody had it that way and therefore it would not make sense to use this library.

Good job, sorry for the confusion.
