### ISSUE TITLE
Feature Request: Better FormKit integration

### ISSUE THREAD

**Issue by joneath** [formkit/auto-animate#2]
I'd love to see some kind of plugin that could be injected into FormKit so we don't have to manually target the `.formkit-outer` class to add `autoAnimate`. For now I've added an `AnimatedForm` wrapper component which does this automatically.

```
<template>
  <div ref="target" class="contents">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import autoAnimate from '@formkit/auto-animate'

const target = ref()

onMounted(() => {
  target.value.querySelectorAll('.formkit-outer').forEach(autoAnimate)
})
</script>
```

**Comment by justin-schroeder** [comment]
Definitely! Great idea 👍

**Comment by justin-schroeder** [comment]
This is now available here: https://formkit.com/plugins/auto-animate

🎉
