### ISSUE TITLE
React.Children.map issue

### ISSUE THREAD

**Issue by asmyshlyaev177** [formkit/auto-animate#201]
Hi, tnx for library, it's good.

But having an issue when children are remapped, take a look on example https://codesandbox.io/p/sandbox/festive-elion-9lhxw5?file=%252Fsrc%252FApp.tsx  and  https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/story/examples-itemsanimation--items-animation

I'm adding empty `div`between children for using it with `scrollIntoView` api.

**Comment by justin-schroeder** [comment]
This is a `key` issue. The root repeated items need to have a unique key — currently they are just cycling dom elements.
