### ISSUE TITLE
Package subpath './vue' is not defined by "exports"

### ISSUE THREAD

**Issue by Oyxiaoxi** [formkit/auto-animate#24]
When I build my application using vite-ssg，

```main.ts
import { autoAnimatePlugin } from '@formkit/auto-animate/vue'

export const createApp = ViteSSG(
  App,
  { routes, scrollBehavior },
  ({ app, router, isClient }) => {
    app.use(autoAnimatePlugin)
    dayjs.extend(LocalizedFormat)
    if (isClient) {
      router.beforeEach(() => { NProgress.start() })
      router.afterEach(() => { NProgress.done() })
    }
  },
)
```

```bash
vite build
```

Package subpath './vue' is not defined by "exports" in /Users/oyxiaoxi/Desktop/Projects/Vue/oyxiaoxi.me/node_modules/@formkit/auto-animate/package.json

**Comment by justin-schroeder** [comment]
Couple questions:

1. What version of node is that running
2. Can you provide a reproduction please

**Comment by Oyxiaoxi** [comment]
@justin-schroeder 

Sorry for wasting your time, it was a problem with my own code ... 😂😂😂
