### ISSUE TITLE
Wrong import in Svelte's example tab

### ISSUE THREAD

**Issue by carusog** [formkit/auto-animate#25]
In home page, Svelte's example tab in hero is showing an import from Vue package.

Current import is `import autoAnimate from "@formkit/vue"`

Expected import should be `import autoAnimate from '@formkit/auto-animate';`

See screenshot:
![CleanShot 2022-06-02 at 12 18 57@2x](https://user-images.githubusercontent.com/124833/171609349-1438514c-50c0-4ea8-a8cd-020339380707.png)

**Comment by justin-schroeder** [comment]
Thanks! Should be fixed now
