### ISSUE TITLE
Feature request: animate when a child is displayed: none in the DOM.

### ISSUE THREAD

**Issue by mohammedsobhi** [formkit/auto-animate#28]
It will be awesome to be able to animate when toggling `display` property to `display: none;` instead of only
![image](https://user-images.githubusercontent.com/63759344/172032242-e78af967-837c-4f2b-bb77-15fa18acb00b.png)

**Comment by Sensiblemnd** [comment]
u could use framer motion for that

**Comment by justin-schroeder** [comment]
Would be cool, but falls outside the scope of this project for now. Maybe we'll revisit this someday in the future.
