### ISSUE TITLE
Vue dropdown example not working? 

### ISSUE THREAD

**Issue by gitFoxCode** [formkit/auto-animate#3]
I rewrote 1:1 the usage example to create a dropdown and I get an error `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

Example:
```
<script setup>
import { ref, onMounted } from "vue"
import autoAnimate from "@formkit/auto-animate"

const dropdown = ref() // we need a DOM node
const show = ref(false)

onMounted(() => {
  autoAnimate(dropdown.value) // thats it!
})
</script>

<template>
  <div ref="dropdown" class="dropdown">
    <strong class="dropdown-label" @click="show = !show"
      >Click me to open!</strong
    >
    <p class="dropdown-content" v-if="show">Lorum ipsum...</p>
  </div>
</template>
```

Code:
https://codesandbox.io/s/broken-tree-e5o9ep?file=/src/App.vue

**Comment by justin-schroeder** [comment]
Looks to me like that codepen isn’t respect the <script setup> syntax sugar. I’ll take a look when I get to work 👍

**Comment by justin-schroeder** [comment]
Yeah, looks like code sandbox’s default Vue 3 sandbox doesn't support `<script setup>` re-written with options api it works:

https://codesandbox.io/s/cool-brook-i8v7lp?file=/src/App.vue

The more you know!

https://media.giphy.com/media/83QtfwKWdmSEo/giphy.gif
