### ISSUE TITLE
Issues with webpack, mjs, exports

### ISSUE THREAD

**Issue by chasegiunta** [formkit/auto-animate#34]
Unfortunately I'm stuck working on this Ember app, and under the surface of it's CLI, it's using Webpack 5. I'm attempting to use the Native JS implementation of AutoAnimate, and running into issues. Importing via `import autoAnimate from '@formkit/auto-animate';` will throw an error:
```
Module not found: Error: Package path . is not exported from package node_modules/@formkit/auto-animate (see exports field in node_modules/@formkit/auto-animate/package.json)
```

Clearly it is. After some research, I think it's an issue with the `.mjs` extension. I know there's been some other issues reported regarding exports as well. 

I personally kind of consider webpack a bit legacy at this point, so if this something that will remain untackled, how is the Native JS implementation _supposed_ to work, given that the docs reference `import autoAnimate from './js/autoAnimate.js'`, and there's no built .js file in the npm module?

**Comment by justin-schroeder** [comment]
I would love to get this resolved better for users across the board. Maybe you can pass along a minimal reproduction of what you're using? Like a little web pack repo, with node version specified etc. Its easily been the biggest issue I've seen with Auto Animate is old webpack folks can't import it properly.

**Comment by deerware** [comment]
Hi @justin-schroeder ,

I've had this exact same issue when trying to import the module and bundle it using webpack. I was able to resolve this by modifying the package.json of your module:

```
    {
      "name": "@formkit/auto-animate",
      "version": "1.0.0-beta.1",
      "description": "Add motion to your apps with a single line of code.",
      "keywords": [
        "animation",
        "transition",
        "react",
        "vue"
      ],
      "type": "module",
      "main": "index.mjs",
      "module": "index.mjs",
      "types": "index.d.ts",
      "repository": "https://github.com/formkit/auto-animate.git",
      "author": "Justin Schroeder <justin@formkit.com>",
      "license": "MIT",
      "exports": {
        "./vue": {
          "import": "./vue/index.mjs",
          "types": "./vue/index.d.ts"
        },
        "./react": {
          "import": "./react/index.mjs",
          "types": "./react/index.d.ts"
        },
-       ".": {
-         "import": "./index.mjs"
-       }
+       ".": [
+         {
+           "import": "./index.mjs"
+         },
+         "./index.mjs"
+       ]
      },
      "dependencies": {},
      "peerDependencies": {
        "react": "^16.8.0",
        "vue": "^3.0.0"
      },
      "peerDependenciesMeta": {
        "vue": {
          "optional": true
        },
        "react": {
          "optional": true
        }
      }
    }
```

I think that it would also resolve #9 and others, if included in their respective exports in the package.json.

I'm not sure whether this is a bug in webpack, or if it should be included you package.json to work correctly, but this solution worked for me.

Let me know if it helps or if you need more information on this issue.

**Comment by justin-schroeder** [comment]
This should be fixed in beta.4
