### ISSUE TITLE
Can't use with esbuild

### ISSUE THREAD

**Issue by nghuuphuoc** [formkit/auto-animate#36]
esbuild produces the following error

```
[error] ✘ [ERROR] Could not resolve "@formkit/auto-animate"
[error]     ../main.js:2:51:
[error]       2 │ ...040formkit$002fauto$002danimate = require("@formkit/auto-animate");
[error]         ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~
[error]   The path "." is not currently exported by package "@formkit/auto-animate":
[error]     ../../../../../node_modules/@formkit/auto-animate/package.json:18:13:
[error]       18 │   "exports": {
[error]          ╵              ^
[error]   None of the conditions provided ("import") match any of the currently active conditions ("browser", "default", "require"):
[error]     ../../../../../node_modules/@formkit/auto-animate/package.json:27:9:
[error]       27 │     ".": {
[error]          ╵          ^
[error]   Consider using an "import" statement to import this file, which will work because the "import" condition is supported by this package:
[error]     ../main.js:2:51:
[error]       2 │ ...040formkit$002fauto$002danimate = require("@formkit/auto-animate");
[error]         ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~
[error]   You can mark the path "@formkit/auto-animate" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

I guess we need to add `default` property to `package.json`:

```json
"exports": {
  ".": {
    "import": "./index.mjs",
    "default": "..."
  }
}
```

**Comment by justin-schroeder** [comment]
Thanks, we'll get this into the next build. Are you able to provide a minimal reproduction that throws this error so we can test various import/export combos? Also relevant information:

- Node version
- OS

**Comment by lspoor** [comment]
Also getting the same, is there a temporary solution for this until a fix is pushed?

<img width="691" alt="Screenshot 2022-06-20 at 11 15 21" src="https://user-images.githubusercontent.com/1685176/174580525-298f0f74-ce6f-4f3b-8bec-5b7f557ae558.png">

**Comment by justin-schroeder** [comment]
Still need node version and os version to begin to trouble shoot this. Most people dont seem to have this issue so its unclear what is different about your installations.

**Comment by nghuuphuoc** [comment]
I don't have enough time to create a minimal repos to reproduce the issue yet, but first here is the information 

* Node version: 

```
$ node -v
v14.17.6
```

* OS version: macOS Monterey 12.4

**Comment by lspoor** [comment]
Node - v14.16.0
OS - macOS Catalina 10.15.17

This is the only library I've ever had this issue with.

**Comment by justin-schroeder** [comment]
@nghuuphuoc Question on this — are you importing this using CommonJS (`require`) instead of using `import`? We don't ship a CJS file at all at the moment.

**Comment by nghuuphuoc** [comment]
@justin-schroeder Our codebase isn't written in JavaScript directly, that's why it is a little bit complicated to create a repos for you.
However, as you can see in the error

```
error] ✘ [ERROR] Could not resolve "@formkit/auto-animate"
[error]     ../main.js:2:51:
[error]       2 │ ...040formkit$002fauto$002danimate = require("@formkit/auto-animate");
```

The code is transpiled to JavaScript via a `require` call. I can't change it because it effects with many JS libs used in our codebase.
This is the only library we have problem with, because the other libs provide CJS compatible build.

**Comment by hyrious** [comment]
I think you can just change `"import"` to `"default"` if you don't want a CJS copy.

**Comment by TheTrio** [comment]
Changing it to `default` would be helpful. I currently have everything transformed to CommonJS before testing with jest and the import for `@formkit/auto-animate` always fails.

**Comment by TheTrio** [comment]
> I think you can just change "import" to "default" if you don't want a CJS copy. Or only enforce the rule at node side:

I tried this locally and it looks like [`@babel/plugin-transform-modules-commonjs`](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) works as expected when the file is `.js` but not `.mjs`. 

I edited the `package.json` in node_modules to look like this (and renamed the file to `index.js` from `index.mjs`)

```js
"exports": {
    ".": {
      "import": "./index.js",
      "default": "./index.js"
    }
}
```
 and everything was fixed.

**Comment by alexandprivate** [comment]
Hi there! Any estimated time to fix this issue? Is happening to me too in the component files and in the test

**Comment by justin-schroeder** [comment]
In theory this should be working now in Beta.4 👍
