### ISSUE TITLE
Peer dependency error while installing 

### ISSUE THREAD

**Issue by guillermo-avalos** [formkit/auto-animate#4]
Trying to test this, but getting the following error:
```
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR!   node_modules/@formkit/auto-animate
npm ERR!     @formkit/auto-animate@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I'm running Node v18.2.0 and React v18.1.0

**Comment by nattwasm** [comment]
Try `npm install @formkit/auto-animate --legacy-peer-deps`, that should fix it!

**Comment by guillermo-avalos** [comment]
That's the recommendation, just wanted to make sure it wouldn't break anything.

**Comment by justin-schroeder** [comment]
Wonder if we should just remove vue and react as `peerDependencies` — they're already marked as optional, but this could be confusing for people.

**Comment by nattwasm** [comment]
Wow! You guys work fast! ⚡️

**Comment by andrew-boyd** [comment]
> @nattwasm Awesome, that fixed it. This literally took 4 seconds: https://www.magnayachts.com/en/second-hands @justin-schroeder 👍🏻 good idea

That's awesome! I like it a yacht. 😛

**Comment by RomainLanz** [comment]
Please note that removing these peer dependencies can cause issues with strict package managers. They prevent importing a package that isn’t installed or listed as a peer dependency, which is true for `react` and `vue`.

If you are using `Yarn`, you need to add the following to your `.yarnrc.yml`:
```yml
packageExtensions:
  "@formkit/auto-animate@*":
    peerDependencies:
      "vue": "*"
```
