### ISSUE TITLE
Is possible work with v-show?

### ISSUE THREAD

**Issue by bilalmalkoc** [formkit/auto-animate#46]
Working perfect with v-if. But v-if is re-rendering components. So it can be not user friendly in some places. For example if accordion got forms and if user filled some forms then, if user toggle accordion, some forms will be empty because of v-if. So v-show is more useful in this case. In your example: https://github.com/formkit/auto-animate/blob/master/docs/src/examples/accordion/ActualAccordion.vue

Is that possible to use auto-animate with v-show directive?

**Comment by justin-schroeder** [comment]
Not currently no. We would need to come up with another observation mechanism for those kinds of mutations. Open to suggestions.
