### ISSUE TITLE
[Vue warn]: A plugin must either be a function or an object with an "install" function.

### ISSUE THREAD

**Issue by jamaluddinrumi** [formkit/auto-animate#48]
### Environment
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `tailwindcss`, `modules`, `colorMode`, `pwa`, `buildModules`, `storyblok`, `build`
- Runtime Modules:  `@kevinmarrec/nuxt-pwa@0.3.1`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `@nuxtjs/tailwindcss@5.1.3`, `@vueuse/nuxt@8.7.5`, `@nuxtjs/partytown@1.2.1`, `@storyblok/nuxt@4.0.1`
------------------------------

### Reproduction
https://github.com/jamaluddinrumi/lemahabang.v3

### Problems
I import `@formkit/auto-animate` through plugin as below
```
/plugins/autoAnimate.js

import { autoAnimate } from "@formkit/auto-animate";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(autoAnimate);
});
```

i got warn 
![Screen Shot 2022-07-05 at 11 56 36 AM](https://user-images.githubusercontent.com/446780/177252477-333fd8e8-86f0-43eb-8bd0-bdfe0fdc0e2a.png)

i also tried to include `@formkit/auto-animate` in build.transpile but it's still the same 
```
/nuxt.config.ts

...
build: {
    transpile: [
      "swiper",
      "@headlessui/vue",
      "@heroicons/vue",
      "@formkit/auto-animate",
      "@fortawesome/vue-fontawesome",
      "@fortawesome/fontawesome-svg-core",
      "@fortawesome/free-solid-svg-icons",
      "@fortawesome/free-brands-svg-icons",
    ],
...
```

**Comment by justin-schroeder** [comment]
Here's a working plugin for ya: https://github.com/jamaluddinrumi/lemahabang.v3/pull/1
