### ISSUE TITLE
Support for React 17 and 18

### ISSUE THREAD

**Issue by kachidk** [formkit/auto-animate#51]
Support for at least react 17 would be appreciated

**Comment by justin-schroeder** [comment]
Should work fine as long as you can do an ESM import

**Comment by luke-ae** [comment]
Not working for me either, error i'm getting:

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @formkit/auto-animate@1.0.0-beta.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.6.5
npm ERR!   node_modules/@headlessui/react
npm ERR!     @headlessui/react@"^1.6.5" from the root project
npm ERR!   peer react@"^17.0.2 || ^18" from @mux/mux-player-react@0.1.0-beta.21
npm ERR!   node_modules/@mux/mux-player-react
npm ERR!     @mux/mux-player-react@"^0.1.0-beta.21" from the root project
npm ERR!   11 more (@trpc/next, @trpc/react, next, next-auth, react-dom, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR! node_modules/@formkit/auto-animate
npm ERR!   @formkit/auto-animate@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR!   node_modules/@formkit/auto-animate
npm ERR!     @formkit/auto-animate@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/lukemacauley/.npm/eresolve-report.txt for a full report.
`

**Comment by nadilas** [comment]
Same here: `peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1`

**Comment by Lukrisum** [comment]
Same here (using pnpm) :
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @formkit/auto-animate
  └── ✕ unmet peer react@^16.8.0: found 18.2.0
```

**Comment by canerd7u** [comment]
+1

**Comment by AndreyYolkin** [comment]
> Same here: `peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1`

I have the same conflict, but with vue. I think we all need to wait until beta 2, because https://github.com/formkit/auto-animate/commit/029b1a6a95b648115fc4d006fe880249457999b1 solves this problem

**Comment by justin-schroeder** [comment]
yeah, all peer dependencies are being removed in beta.2 because it seems package managers dont do a great job of respecting the "optional" property. Mia culpa on that.

**Comment by nadilas** [comment]
You could have stopped at package managers don’t do a great job. 😂 no need to specify.

when is beta 2 expected to drop?

**Comment by nawed2611** [comment]
Hey, I'm facing the same issue

**Comment by luke-ae** [comment]
It does work fine when you use --force

**Comment by AndreyYolkin** [comment]
I don't want to use `--force`, which can possibly broke other dependency resolutions, that's why I temporarily removed lib from project

**Comment by kristian-puccio** [comment]
works for me but I'm using pnpm

**Comment by one2code** [comment]
Same problem.  Was really excited to take this package out for a spin after seeing Theo use it, but then I got slapped with this:

`npm ERR! While resolving: @formkit/auto-animate@1.0.0-beta.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0 || ^18.0.0" from @apollo/client@3.6.9
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.6.9" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0-rc.1 || ^18.0.0" from @react-aria/ssr@3.2.0
npm ERR!   node_modules/@react-aria/ssr
npm ERR!     @react-aria/ssr@"^3.2.0" from @restart/ui@1.3.0
npm ERR!     node_modules/@restart/ui
npm ERR!       @restart/ui@"^1.2.0" from react-bootstrap@2.4.0
npm ERR!       node_modules/react-bootstrap
npm ERR!         react-bootstrap@"^2.4.0" from the root project
npm ERR!   11 more (@restart/hooks, @restart/ui, prop-types-extra, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR! node_modules/@formkit/auto-animate
npm ERR!   @formkit/auto-animate@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR!   node_modules/@formkit/auto-animate
npm ERR!     @formkit/auto-animate@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution`

Hopefully soon.

**Comment by LucaDiba** [comment]
> all peer dependencies are being removed in beta.2

I've just tried to install the package by ignoring the dependencies, however it seems that there are some TypeScript issues that have to be fixed, so I'm not sure whether making the dependencies optional would solve the issue @justin-schroeder.
Or maybe this is not related to the dependencies?

```
(property) ClassAttributes<HTMLDivElement>.ref?: LegacyRef<HTMLDivElement> | undefined
Type 'RefObject<Element>' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.
  Type 'RefObject<Element>' is not assignable to type 'RefObject<HTMLDivElement>'.
    Type 'Element' is missing the following properties from type 'HTMLDivElement': align, accessKey, accessKeyLabel, autocapitalize, and 114 more.ts(2322)
index.d.ts(137, 9): The expected type comes from property 'ref' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'
```

**Comment by luke-ae** [comment]
@LucaDiba you need to use `const [yourRef] = useAutoAnimate<HTMLDivElement>();`

**Comment by perfectbase** [comment]
as a workaround for now, I added the following to my `package.json`

```
  "overrides": {
    "react": "18.2.0"
  }
```

It's working for me... but I would prefer not to have to use this.

**Comment by LucaDiba** [comment]
> @LucaDiba you need to use `const [yourRef] = useAutoAnimate<HTMLDivElement>();`

Thanks @luke-ae!
Is there a reason why we should specify the generics?
Also, all the examples use auto animate in a `div` but do not specify the type: is there something different in my case? Should the docs be updated or this is kinda a bug and will be fixed in the future?

**Comment by luke-ae** [comment]
@LucaDiba not 100% sure but you're getting a typescript error telling you that you need to add that in. I don't think it matters if it's a div or not.

**Comment by perfectbase** [comment]
@LucaDiba 
The examples in the docs are in JavaScript.
If you are using TypeScript, the ref needs to be of the right type for you to set it in an element.
The generic is used internally to cast the ref type.

(I do think it's important to have typescript examples in the docs, though)

**Comment by kasparsuvi1** [comment]
> 

To only override '@formkit/auto-animate' react dependencie you can do: (Still not ideal solution, but better)
```
 "overrides": {
    "@formkit/auto-animate": {
      "react": "17.0.2"
    }
  },
```

**Comment by savin2001** [comment]
> Not working for me either, error i'm getting:
> 
> `npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: @formkit/auto-animate@1.0.0-beta.1 npm ERR! Found: react@18.2.0 npm ERR! node_modules/react npm ERR! peer react@"^16 || ^17 || ^18" from @headlessui/react@1.6.5 npm ERR! node_modules/@headlessui/react npm ERR! @headlessui/react@"^1.6.5" from the root project npm ERR! peer react@"^17.0.2 || ^18" from @mux/mux-player-react@0.1.0-beta.21 npm ERR! node_modules/@mux/mux-player-react npm ERR! @mux/mux-player-react@"^0.1.0-beta.21" from the root project npm ERR! 11 more (@trpc/next, @trpc/react, next, next-auth, react-dom, ...) npm ERR! npm ERR! Could not resolve dependency: npm ERR! peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1 npm ERR! node_modules/@formkit/auto-animate npm ERR! @formkit/auto-animate@"*" from the root project npm ERR! npm ERR! Conflicting peer dependency: react@16.14.0 npm ERR! node_modules/react npm ERR! peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1 npm ERR! node_modules/@formkit/auto-animate npm ERR! @formkit/auto-animate@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See /Users/lukemacauley/.npm/eresolve-report.txt for a full report. `

Same here too

**Comment by justin-schroeder** [comment]
This should be fixed in the latest betas since we removed `peerDependencies` all together

**Comment by LinnJS** [comment]
Just wanted to note that [this comment](https://github.com/formkit/auto-animate/issues/51#issuecomment-1198936912) fixed [this error](https://github.com/formkit/auto-animate/issues/51#issuecomment-1198933648) for me. 🙂

**Comment by mohanbishnoi** [comment]
Better not to use autoAnimate use useRef instead resolves all issues
