### ISSUE TITLE
react-native-web support (react-dom)

### ISSUE THREAD

**Issue by johkade** [formkit/auto-animate#58]
Hey everybody! What an amazing library! 🤩

Since auto-animate easily works with react / react-dom and react-native-web is just a layer on top (also using react-dom)
I was wondering auto-animate it should not work out of the box for react-native-web.

Sadly, it doesn't it seems.

Does anybody have a hint on how to get it to work or what would be the missing piece?

Just to clarify: I'm not talking about React Native for ios/android since I have react-native-reanimated for that.
I'm talking about react-native-web which is just an abstraction layer for react/react-dom.

Thanks for any input on that!

**Comment by justin-schroeder** [comment]
I’m guessing prefers-reduced-motion is enabled for some reason, if it is not and you can provide a reproduction we can open this back up.
