### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by imdkbj** [formkit/auto-animate#6]
Can we have support for react native.

**Comment by justin-schroeder** [comment]
Sadly, no. React Native doesn't have use DOM elements, so the entire thing would be need to be re-written specifically for that. Although....maybe someday

**Comment by canerd7u** [comment]
+1 @justin-schroeder you can ?

**Comment by hichemfantar** [comment]
How difficult would it be to write a [rn reanimated](https://docs.swmansion.com/react-native-reanimated/) integration?
