### ISSUE TITLE
docs: Svelte quickstart example

### ISSUE THREAD

**Issue by MentalGear** [formkit/auto-animate#60]
First: thx for this great library !

As a new user, I tried integrating autoanimate with the svelte example on the main page, yet no animation was played. Then I remembered that svelte requires a _key_ to keep track of changes.

It would be great if the example provided would have a key defined as well:
```svelte
    {#each tags as tag (tag)}
```

**Comment by justin-schroeder** [comment]
Sounds great! would you mind submitting a PR for this change @MentalGear?

**Comment by MentalGear** [comment]
There we go
https://github.com/formkit/auto-animate/pull/78
