### ISSUE TITLE
Vite React app v18 support

### ISSUE THREAD

**Issue by savin2001** [formkit/auto-animate#63]
I  am using the latest Vite React App with TS and for styling, I am using Tailwind CSS. Do you support the latest React app v18 or am I forced to roll back? When I tried to install this animation library I got the error below:
`>npm install @formkit/auto-animate
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @formkit/auto-animate@1.0.0-beta.1    
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.6.6
npm ERR!   node_modules/@headlessui/react
npm ERR!     @headlessui/react@"^1.6.6" from the root project   
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^16 || ^17 || ^18" from @headlessui/react@1.6.6
npm ERR!     node_modules/@headlessui/react
npm ERR!       @headlessui/react@"^1.6.6" from the root project 
npm ERR!     peer react-dom@"^16.0.0 || ^17.0.0 || ^18.0.0" from react-resize-detector@7.1.2
npm ERR!     node_modules/react-resize-detector
npm ERR!       react-resize-detector@"^7.1.2" from recharts@2.1.13
npm ERR!       node_modules/recharts
npm ERR!         recharts@"^2.1.13" from the root project       
npm ERR!     5 more (react-router-dom, react-smooth, ...)       
npm ERR!   11 more (react-helmet, react-icons, react-resize-detector, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR! node_modules/@formkit/auto-animate
npm ERR!   @formkit/auto-animate@"*" from the root project      
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0" from @formkit/auto-animate@1.0.0-beta.1
npm ERR!   node_modules/@formkit/auto-animate
npm ERR!     @formkit/auto-animate@"*" from the root project    
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps       
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-08-04T09_52_11_683Z-debug-0.log`

**Comment by icebearlabs** [comment]
Opened a PR for this: https://github.com/formkit/auto-animate/pull/64

**Comment by icebearlabs** [comment]
For the time now: @savin2001 you can override the version in npm: 

See also here: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

This is what works for me: 

```
  "overrides": {
    "@formkit/auto-animate": {
      "react": "$react"
    }
  }
```

**Comment by justin-schroeder** [comment]
This shouldnt be a problem with beta.3 👍peerDependencies are gonzo
