### ISSUE TITLE
Not working with Vue KeepAlive

### ISSUE THREAD

**Issue by bilalmalkoc** [formkit/auto-animate#79]
For some reasons we need to use [KeepAlive](https://vuejs.org/guide/built-ins/keep-alive.html) tag in Vue. But animations now working with this.

Live example here: [CodeSandbox](https://codesandbox.io/s/small-dust-7k8yt8?file=/src/App.vue:60-69)

**Comment by suman-majhi** [comment]
@bilalmalkoc got some workaround for this issue
Use a single `<KeepAlive>` tag around the components
Somehow, `v-auto-animate` fails to animate multiple `<KeepAlive>` children
Actually it's working for the first toggle/load  

Here is the code snippet: 
```
<KeepAlive>
  <div v-auto-animate>
    <CompOne v-if="toggle" />
    <CompTwo v-if="!toggle" />
  </div>
</KeepAlive>
```
Hope this will fix your problem with the code
