### ISSUE TITLE
"options" param in the "useAutoAnimate" hook isn't optional

### ISSUE THREAD

**Issue by apenab** [formkit/auto-animate#88]
Hi there! Seems to be that the `options` param in the `useAutoAnimate` hook isn't optional, I'm receiving this error: 

![image](https://user-images.githubusercontent.com/22795807/192150366-1f09c070-cd7f-4aa0-a3df-be2e8cba3fe4.png)

**Comment by justin-schroeder** [comment]
Are you using beta.3? I believe this was fixed in that release.

**Comment by apenab** [comment]
@justin-schroeder 

"@formkit/auto-animate": "^1.0.0-beta.3",
